# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.box_check_update = false

  config.vm.define "master" do |master|
    master.vm.hostname = "wiki"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "forwarded_port", guest: 80, host: 8181
    master.vm.provision :shell, path: "Scripts/cron.sh", privileged: false
    # master.vm.provision "shell", inline: "ssh-keyscan -t rsa 192.168.33.11 > ~/.ssh/known_hosts"
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.168.33.11"
    backup.vm.network "forwarded_port", guest: 80, host: 8282
    # backup.vm.provision "shell", inline: "ssh-keyscan -t rsa 192.168.33.11 > ~/.ssh/known_hosts"
  end

config.vm.provision "shell", inline: <<-SHELL
  export DEBIAN_FRONTEND=noninteractive

  echo "==> Mise à jour"
  sudo apt-get update -y

  echo "==> Installation des dépendances"
  sudo apt-get install php-geshi -y

  echo "==>  Téléchargement et extractionn de Dokuwiki"
  cd /tmp
  wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
  tar -xvf dokuwiki-stable.tgz

  echo "==>  Déplacement de Dokuwiki"
  sudo rm /var/www/html/index.html
  sudo cp -r dokuwiki-2018-04-22b/* /var/www/html/
  sudo chown -R vagrant:www-data /var/www/html/
  SHELL

  # SSH
  config.vm.provision "file", source: "Keys/vagrant_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "Keys/vagrant_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
  config.vm.provision "file", source: "Keys/vagrant_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell, path: "Scripts/keys.sh", privileged: false
end
