#!/bin/bash

# Variables
## Dossier à sauvegarder
BACKUPFOLDER=$1

## Dossier de destination pour le fichier de sauvegarde 'save.tar'
DESTFOLDER=$2

## Options du script
OPTION=$3

## Time, Date and name Variable
FRIDAY="5"
TODAY=`date +%u`
DATE=`date +%Y-%m-%d`
DATETIME=`date '+%Y-%m-%d_%H:%M:%S'`
DESTFILENAME=""
CRONSCRIPT=~/autosave.sh
CRONLINE="00 03 * * 5 $CRONSCRIPT"



# Fonction aide
usages() {
    echo -e "Utilisation du scripts de sauvegarde :\n
    ./save_script FOLDER_TO_BACKUP DESTINATION_FOLER/ OPTION\n
    AVANT TOUT VERIFIEZ QUE VOUS AVEZ LES BONS DROITS SUR LES DOSSIER SINON UTILISEZ sudo !\n
    Les options disponibles sont :\n
        ponctual : Sauvegarde immédiate\n
        enable : Activer le service de sauvegarde tous les vendredi\n
        disable : Désinstaller le service\n
        check : Vérifier la présence les tâche à démarrage automatique\n
        list : List les fichiers du dossier de destination de la sauvegarde\n
    "
    echo -e "Utilisez ./save_script --help ou ./save_script -h pour afficher ce message."
    
}

# Fonction sauvegarde

## Sauvegarde Incrémentable
save() {
    # echo 'test save ok'
    if [[ -e $DESTFOLDER/increment.list ]]; then
        MAX=`ls | cut -c-1 | sort -n | tail -1`
        
    else
        touch $DESTFOLDER/increment.list
        MAX="0"
    fi;
    
    if [ $TODAY -ge $FRIDAY ]; then
        MAX=$(( $MAX + 1 ))
        DESTFILENAME="$MAX-savefull.tar"
        tar --create --file="$DESTFILENAME" --listed-incremental="$DESTFOLDER/increment.list" "$BACKUPFOLDER" 2>/dev/null
    else
        DESTFILENAME="$MAX-$DATETIME-save.tar"
        tar --create --file="$DESTFILENAME" --listed-incremental="$DESTFOLDER/increment.list" "$BACKUPFOLDER" 2>/dev/null
    fi;
    
    find $DESTFOLDER -mtime +30 -type f -delete
    echo "Sauvegarde effectuée"
}

## Activation sauvegarde automatique
enable_auto_save() {
    # echo 'test enable_auto_save ok'
    test -f $CRONSCRIPT || touch $CRONSCRIPT
    echo "
#!/bin/bash

MAX=""
DESTFILENAME=""
DATETIME=`date '+%Y-%m-%d_%H:%M:%S'`

if [[ -e $DESTFOLDER/increment.list ]]; then
    MAX=`ls | cut -c-1 | sort -n | tail -1`

else
    touch $DESTFOLDER/increment.list
    MAX="0"
fi;

if [ $TODAY -ge $FRIDAY ]; then
    MAX=$(( $MAX + 1 ))
    DESTFILENAME="$MAX-savefull.tar"
    tar --create --file="$DESTFILENAME" --listed-incremental="$DESTFOLDER/increment.list" "$BACKUPFOLDER" 2>/dev/null
else
    DESTFILENAME="$MAX-$DATETIME-save.tar"
    tar --create --file="$DESTFILENAME" --listed-incremental="$DESTFOLDER/increment.list" "$BACKUPFOLDER" 2>/dev/null
fi;

find $DESTFOLDER -mtime +30 -type f -delete
    " >> $CRONSCRIPT
    chmod +x $CRONSCRIPT
    (crontab -u $USER -l; echo "$CRONLINE";) | crontab -u $USER -
    clear
    echo "Sauvegarde automatique activée"
    
}

## Désactivation sauvegarde automatique
disable_auto_save() {
    # echo 'test disable_auto_save ok'
    crontab -u $USER -l | grep -v "$CRONSCRIPT" | crontab -u $USER -
    rm -f $CRONSCRIPT
    clear
    echo "Sauvegarde automatique désactivée"
}

## Vérification des taches automatiques
check_cron() {
    crontab -u $USER -l
}

## List des fichiers du dossier de destination
show_life() {
    ls -la $DESTFOLDER
}

[ -d $DESTFOLDER ] || mkdir -p $DESTFOLDER
if [[ ($1 = "--help") || ($1 = "-h") ]]; then
    usages
    exit 1
    elif [[ ($OPTION = "save") ]] ; then
    save
    exit 1
    elif [[ ($OPTION = "enable") ]] ; then
    enable_auto_save
    exit 1
    elif [[ ($OPTION = "disable") ]] ; then
    disable_auto_save
    exit 1
    elif [[ ($OPTION = "check") ]] ; then
    check_cron
    exit 1
    elif [[ ($1 = "check") ]]; then
    check_cron
    exit 1
    elif [[ ($OPTION = "show") ]] ; then
    show_life
    exit 1
    
else
    echo -e "Commande Invalide\n"
    usages
fi;
