#!/bin/bash

# Variables

# Fonction aide
usages() {
    echo -e "Utilisation du scripts de sauvegarde :\n
    ./save_script --backupfoler='/FOLDER_TO_BACKUP' --destfoler='/DESTINATION_FOLER/save_file.tar' --option='OPTION'\n
    Les options disponibles sont :\n
        ponctual : Sauvegarde immédiate\n
        enable : Activer le service de sauvegarde tous les vendredi\n
    disable : Désinstaller le service"
    
}

# Fonction sauvegarde

ponctual_save() {
    echo 'test ponctual_save ok'
}

enable_auto_save() {
    echo 'test enable_auto_save ok'
}

disable_auto_save() {
    echo 'test disable_auto_save ok'
}

# Script
## Afficher l'aide
if [[ ($1 == "--help") || ($1 == "-h") ]]; then
    usages
    
    ## L'utilisation des conditions en utilisant "||" ne fait pas tous les test donc l'indentation est moche en faisant conditions sur conditions, ce n'est pas du tout optimisé mais ça permet un gain de temps et est voué à être modifier par la suite !
    
    
    elif [[ ($1 == "--backupfolder="*) ]]; then
    if [[ ($1 != "--backupfolder=") ]]; then
        if [[ ($2 = "--destfolder="*) ]]; then
            if [[ ($2 != "--destfolder=") ]]; then
                if [[ ($3 = "--option=ponctual") ]]; then
                    ponctual_save
                    
                    elif [[ ($3 = "--option=enable") ]]; then
                    enable_auto_save
                    
                    elif [[ ($3 = "--option=disable") ]]; then
                    disable_auto_save
                else
                    echo -e "Erreur d'argument !\n"
                    usages
                fi
            fi
        fi
    fi
fi

