# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 07 Oct 2019 20:59:48 +0000
*               @ALL          1
*               @user         8
