<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: too late
 */
$conf['title'] = 'lab wiki';
$conf['lang'] = 'en';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
